name: Ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checks out your repository
      - uses: actions/setup-python@v5 # Sets up a Python environment
        with:
          python-version: '3.11' # Specify your Python version
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check . --output-format=github # Runs Ruff to check for errors and generates inline annotations in PRs
